RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 2
CHUNK_SIZE: 500
CHUNK_OVERLAP: 150
DATA_PATH: 'data/'
LOG_FILE: 'log_loaded.txt'
DB_FAISS_PATH: 'vectorstore/db_faiss'
MAX_NEW_TOKENS: 256
TEMPERATURE: 0.01
EMBEDDINGS_MODEL_NAME: 'sentence-transformers/all-MiniLM-L12-v2' 